Repository Yalantis/Koloda, pull requests merged in 2018-08, with the labels that each got.

#363 Fix Swift 4.1 warning
  Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
Labels: priority: high, status: work in progress, type: enhancement

#376 Fix issue #375
  Pod/Classes/KolodaView/KolodaViewAnimatior.swift
Labels: priority: medium, status: work in progress, type: bug

#357 Add isLoop property for looping cards
  Pod/Classes/KolodaView/KolodaView.swift
Labels: priority: medium, status: work in progress, type: enhancement

#367 Update README.md
  README.md
Labels: priority: low, status: work in progress, type: bug

#358 Added delegate function for pan gesture
  Pod/Classes/KolodaView/DraggableCardView/DraggableCardView.swift
  Pod/Classes/KolodaView/KolodaView.swift
Labels: priority: low, status: work in progress, type: enhancement
